[package]
name = "zja-cryptopals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
openssl = { version = "0.10.45", features = ["vendored"] }
rand = "0.8.5"
